<?php
/**
 * Functions.php contains all the core functions for your theme to work properly.
 * Please do not edit this file!!
 *
 * @package WordPress
 * @subpackage GoodInc
 */

 ini_set('error_reporting', E_ALL);
 ini_set('display_errors', 1);
 ini_set('display_startup_errors', 1);


/**
 * Define Constants
 * @since 1.0
*/
define( 'WPEX_JS_DIR', get_template_directory_uri().'/js' );
define( 'WPEX_CSS_DIR', get_template_directory_uri().'/css' );


/**
 * Admin Functions
 * @since 1.0
*/
require_once( get_template_directory() .'/functions/return-smof-data.php' );

/**
* Main functions
* @since 1.0
*/

// Define widget areas and add custom widgets
require_once( get_template_directory() .'/functions/scripts.php' );

// Custom fonts
require_once( get_template_directory() .'/functions/google-fonts.php' );

// AJAX Load More Function
require_once( get_template_directory() .'/functions/load-more.php' );
